name: get-iplayer # you probably want to 'snapcraft register <name>'
version: '1'
summary: CLI for downloading content from BBC iplayer
description: |
    Command Line tool for downloading tv and radio programmes from the last 30 days from the BBC iPlayer.

grade: devel 
confinement: devmode

apps:
    get-iplayer:
        command: wrapper.sh
        plugs:
        - network 

parts:
    get-iplayer:
        source: https://github.com/get-iplayer/get_iplayer.git
        plugin: dump
        stage-packages:
        - perl
        - libwww-perl
        - liblwp-protocol-https-perl
        - libmojolicious-perl
        - libxml-simple-perl
        - libxml-libxml-perl
        - libcgi-pm-perl
        - atomicparsley
        - ffmpeg
    wrapper:
      plugin: nil
      source: .
      install: |
        cp wrapper.sh $SNAPCRAFT_PART_INSTALL/
      after:
        - get-iplayer
